(package "better-scroll"
         "0.1.4"
         "Improve user experience when scrolling window")

(website-url "https://github.com/jcs-elpa/better-scroll")
(keywords "scrolling" "scroll" "window" "better" "improvement")

(package-file "better-scroll.el")

(source "melpa")

(depends-on "emacs" "24.3")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
